name: Node Setup concurrency
on:  
    push:
        branches: [main]   

jobs:
    node-setup-jobs:
      runs-on: ubuntu-latest  

      steps:
          - name: Checkout Repo 
            uses: actions/checkout@v4 

          - name: Initialize Node 
            uses : actions/setup-node@v4
